### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by aradove** [foxmask/baeuda#4]
Hi.

Your repo/instructions is unclear. 

1. You should add and requirements file so one can install all the required libraries. For python, one need joplin_api, pypandoc, requests and also one need to install pandoc. 

2. Add a link to instructions how to add clipper.

3. The instructions for settings.py is unclear. 
- What is FOLDER? Is it a Joplin notebook or note?
- What is model? There does not exist anything named model in anki.
- Add an basic note example. 

Best regards

**Comment by foxmask** [comment]
of course model exist in anki :) the anki api speaks about model. 
from the anki menu : 
"Tools > Manage Type of Note"

How baeuda works:
1) anki use a type of note with given name of field
2) in joplin we build our table with the exact same name of anki field
thus baeuda will be able to map 1 to 2 

In the README I said:
```
ANKI_FIELDS = ['Coréen', 'Romanisation', 'Français']  # the name of the fields from the anki model 
```
and if you look at the image https://raw.githubusercontent.com/foxmask/baeuda/master/joplin_notes.png
you see the headers with that 3 fields name 
and if you look at the image https://raw.githubusercontent.com/foxmask/baeuda/master/anki_card.png you also see the 3 fields name

I will try to clarify the instructions
